/* Generated by AN DISI Unibo */ 
package it.unibo.sonar

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
class Sonar ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
				return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("alarm - sonar started")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_work", 
				 	 					  scope, context!!, "local_tout_sonar_work", 3000.toLong() )
					}	 	 
					 transition(edgeName="t00",targetState="stop",cond=whenTimeout("local_tout_sonar_work"))   
				}	 
				state("stop") { //this:State
					action { //it:State
						forward("stop", "stop(1)" ,"planexec" ) 
						CommUtils.outgreen("alarm - sent stop")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_stop", 
				 	 					  scope, context!!, "local_tout_sonar_stop", 2000.toLong() )
					}	 	 
					 transition(edgeName="t11",targetState="continue",cond=whenTimeout("local_tout_sonar_stop"))   
				}	 
				state("continue") { //this:State
					action { //it:State
						forward("continue", "continue(1)" ,"planexec" ) 
						CommUtils.outgreen("alarm - sent continue")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_continue", 
				 	 					  scope, context!!, "local_tout_sonar_continue", 10000.toLong() )
					}	 	 
					 transition(edgeName="t12",targetState="work",cond=whenTimeout("local_tout_sonar_continue"))   
				}	 
			}
		}
} 
